export const products = [
  {
    id: 1,
    name: 'Sneakers Court Minimalis',
    category: 'Shoes',
    code: 'SH',
    price: 275000,
    rating: 4.9,
    src: '/src/public/images/products/product-image1.png',
  },
  {
    id: 2,
    name: 'Kaos Crewneck Esensial',
    category: 'Shirts',
    code: 'SHI',
    price: 800000,
    rating: 4.8,
    src: '/src/public/images/products/product-image2.png',
  },
  {
    id: 3,
    name: 'Tas Selempang Klasik',
    category: 'Accessories',
    code: 'ACC',
    price: 1600000,
    rating: 4.7,
    src: '/src/public/images/products/product-image3.png',
  },
  {
    id: 4,
    name: 'Kaos Soft Touch',
    category: 'Shirts',
    code: 'SHI',
    price: 650000,
    rating: 4.6,
    src: '/src/public/images/products/product-image4.png',
  },
  {
    id: 5,
    name: 'Overshirt Utility',
    category: 'Shirts',
    code: 'SHI',
    price: 375000,
    rating: 4.5,
    src: '/src/public/images/products/product-image5.png',
  },
  {
    id: 6,
    name: 'Sweater Rajut Cable',
    category: 'Shirts',
    code: 'SHI',
    price: 1300000,
    rating: 4.8,
    src: '/src/public/images/products/product-image6.png',
  },
  {
    id: 7,
    name: 'Syal Wol Kotak',
    category: 'Accessories',
    code: 'ACC',
    price: 220000,
    rating: 4.9,
    src: '/src/public/images/products/product-image7.png',
  },
  {
    id: 8,
    name: 'Syal Wol Solid',
    category: 'Accessories',
    code: 'ACC',
    price: 180000,
    rating: 4.7,
    src: '/src/public/images/products/product-image8.png',
  },
  {
    id: 9,
    name: 'Celana Panjang',
    category: 'Pants',
    code: 'PAN',
    price: 2200000,
    rating: 4.8,
    src: '/src/public/images/products/product-image9.png',
  },
  {
    id: 10,
    name: 'Sneakers Harian',
    category: 'Shoes',
    code: 'SH',
    price: 1900000,
    rating: 4.9,
    src: '/src/public/images/products/product-image10.png',
  },
  {
    id: 11,
    name: 'Jaket Puffer Quilted',
    category: 'Shirts',
    code: 'SHI',
    price: 450000,
    rating: 4.6,
    src: '/src/public/images/products/product-image11.png',
  },
  {
    id: 12,
    name: 'Kemeja Oxford',
    category: 'Shirts',
    code: 'SHI',
    price: 950000,
    rating: 4.8,
    src: '/src/public/images/products/product-image12.png',
  },
  {
    id: 13,
    name: 'Celana Pendek Chino',
    category: 'Pants',
    code: 'PAN',
    price: 120000,
    rating: 4.5,
    src: '/src/public/images/products/product-image13.png',
  },
  {
    id: 14,
    name: 'Topi Baseball 6-Panel',
    category: 'Accessories',
    code: 'ACC',
    price: 320000,
    rating: 4.7,
    src: '/src/public/images/products/product-image14.png',
  },
  {
    id: 15,
    name: 'Kaos Katun Premium',
    category: 'Shirts',
    code: 'SHI',
    price: 1100000,
    rating: 4.9,
    src: '/src/public/images/products/product-image15.png',
  },
  {
    id: 16,
    name: 'Hoodie Pullover Fleece',
    category: 'Shirts',
    code: 'SHI',
    price: 275000,
    rating: 4.8,
    src: '/src/public/images/products/product-image16.png',
  },
];
